"""Final touches to Many to many relationship

Revision ID: 969e4d097e21
Revises: b09c097a3d5b
Create Date: 2022-05-14 23:52:23.939882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '969e4d097e21'
down_revision = 'b09c097a3d5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'shop', ['shop_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'categories', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_column('shop', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('category', sa.VARCHAR(length=80), nullable=False))
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'shop', ['shop_id'], ['id'])
    op.create_foreign_key(None, 'categories', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###
